#!/usr/bin/env python3
"""AAP Controller helper for ansible.builtin.package.

Generated by AnsibleClaw -- uses only Python stdlib (urllib + json).
Launches ad-hoc commands or job templates via the AAP Controller REST API,
polls for completion, and prints structured JSON output.

Environment variables:
    AAP_CONTROLLER_URL    Base URL of the AAP/AWX controller (required)
    AAP_CONTROLLER_TOKEN  OAuth2 bearer token (required)
    AAP_VERIFY_SSL        Set to 'false' to skip TLS verification (default: true)
    AAP_DEFAULT_INVENTORY Inventory name or ID to use when not specified
    AAP_DEFAULT_CREDENTIAL Credential name or ID to use when not specified
"""

from __future__ import annotations

import argparse
import json
import os
import ssl
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

MODULE = "ansible.builtin.package"

# ---------------------------------------------------------------------------
# Configuration from environment
# ---------------------------------------------------------------------------

def _cfg():
    url = os.environ.get("AAP_CONTROLLER_URL", "").rstrip("/")
    token = os.environ.get("AAP_CONTROLLER_TOKEN", "")
    if not url or not token:
        print(
            "Error: AAP_CONTROLLER_URL and AAP_CONTROLLER_TOKEN must be set.",
            file=sys.stderr,
        )
        sys.exit(1)
    verify = os.environ.get("AAP_VERIFY_SSL", "true").lower() in ("true", "1", "yes")
    return url, token, verify


def _ssl_context(verify: bool) -> ssl.SSLContext | None:
    if not verify:
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
        return ctx
    return None


# Cache the detected API prefix so we only probe once per run.
_api_prefix: str | None = None


def _detect_api_prefix(base_url: str, token: str, verify: bool) -> str:
    """Probe /api/v2 and /api/controller/v2 (AAP 2.5 gateway) and return
    whichever responds first. The result is cached for the process lifetime."""
    global _api_prefix
    if _api_prefix is not None:
        return _api_prefix
    for prefix in ("/api/v2", "/api/controller/v2"):
        try:
            _request("GET", f"{base_url}{prefix}/ping/", token, verify, fatal=False)
            _api_prefix = prefix
            return prefix
        except AAPRequestError:
            continue
    _api_prefix = "/api/v2"
    return _api_prefix


def _api(base_url: str, token: str, verify: bool, path: str) -> str:
    """Build a full API URL using the auto-detected prefix.

    ``path`` should start with ``/`` and be relative to the API root,
    e.g. ``/inventories/``, ``/job_templates/42/launch/``.
    """
    prefix = _detect_api_prefix(base_url, token, verify)
    return f"{base_url}{prefix}{path}"


# ---------------------------------------------------------------------------
# HTTP helpers
# ---------------------------------------------------------------------------

class AAPRequestError(Exception):
    """Raised when an AAP API request fails."""


def _request(method: str, url: str, token: str, verify: bool,
             data: dict | None = None, *, fatal: bool = True) -> dict:
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }
    body = json.dumps(data).encode() if data else None
    req = urllib.request.Request(url, data=body, headers=headers, method=method)
    ctx = _ssl_context(verify)
    try:
        with urllib.request.urlopen(req, context=ctx, timeout=30) as resp:
            raw = resp.read().decode()
            return json.loads(raw) if raw.strip() else {}
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode() if exc.fp else ""
        msg = f"HTTP {exc.code} from {url}: {detail}"
        if fatal:
            print(msg, file=sys.stderr)
            sys.exit(1)
        raise AAPRequestError(msg)
    except urllib.error.URLError as exc:
        msg = f"Connection error: {exc.reason}"
        if fatal:
            print(msg, file=sys.stderr)
            sys.exit(1)
        raise AAPRequestError(msg)


def _get(url: str, token: str, verify: bool) -> dict:
    return _request("GET", url, token, verify)


def _post(url: str, token: str, verify: bool, data: dict) -> dict:
    return _request("POST", url, token, verify, data)


# ---------------------------------------------------------------------------
# Resource lookup helpers
# ---------------------------------------------------------------------------

def _resolve_id(base_url: str, token: str, verify: bool,
                resource: str, name_or_id: str) -> int:
    """Resolve a resource name or numeric ID to a numeric ID."""
    if name_or_id.isdigit():
        return int(name_or_id)
    url = _api(base_url, token, verify, f"/{resource}/?name={urllib.parse.quote(name_or_id)}")
    result = _get(url, token, verify)
    items = result.get("results", [])
    if not items:
        print(f"Error: {resource} '{name_or_id}' not found.", file=sys.stderr)
        sys.exit(1)
    return items[0]["id"]


# ---------------------------------------------------------------------------
# Job polling
# ---------------------------------------------------------------------------

TERMINAL_STATES = {"successful", "failed", "error", "canceled"}

def _poll_job(base_url: str, token: str, verify: bool,
              job_url: str, interval: float = 3.0) -> dict:
    """Poll a job/command until it reaches a terminal state."""
    full_url = job_url if job_url.startswith("http") else f"{base_url}{job_url}"
    while True:
        job = _get(full_url, token, verify)
        status = job.get("status", "unknown")
        if status in TERMINAL_STATES:
            return job
        print(f"  Status: {status} ... waiting {interval}s", file=sys.stderr)
        time.sleep(interval)


def _get_stdout(base_url: str, token: str, verify: bool,
                job_url: str) -> str:
    """Retrieve the stdout text from a completed job."""
    full_url = job_url if job_url.startswith("http") else f"{base_url}{job_url}"
    stdout_url = f"{full_url}stdout/?format=json"
    result = _get(stdout_url, token, verify)
    return result.get("content", result.get("result_stdout", ""))


# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------

def cmd_adhoc(args: argparse.Namespace) -> None:
    """Launch an ad-hoc command for ansible.builtin.package."""
    base_url, token, verify = _cfg()

    inventory = args.inventory or os.environ.get("AAP_DEFAULT_INVENTORY", "")
    credential = args.credential or os.environ.get("AAP_DEFAULT_CREDENTIAL", "")
    if not inventory:
        print("Error: --inventory or AAP_DEFAULT_INVENTORY is required.", file=sys.stderr)
        sys.exit(1)
    if not credential:
        print("Error: --credential or AAP_DEFAULT_CREDENTIAL is required.", file=sys.stderr)
        sys.exit(1)

    inv_id = _resolve_id(base_url, token, verify, "inventories", inventory)
    cred_id = _resolve_id(base_url, token, verify, "credentials", credential)

    payload = {
        "inventory": inv_id,
        "credential": cred_id,
        "module_name": MODULE,
        "module_args": args.module_args,
        "limit": args.limit or "",
        "become_enabled": not args.no_become,
    }

    if args.check:
        payload["diff_mode"] = True
        payload["extra_vars"] = json.dumps({"ansible_check_mode": True})

    print(f"==> Launching ad-hoc: {MODULE} on inventory {inv_id}", file=sys.stderr)
    result = _post(_api(base_url, token, verify, "/ad_hoc_commands/"), token, verify, payload)

    job_url = result.get("url", f"{_detect_api_prefix(base_url, token, verify)}/ad_hoc_commands/{result['id']}/")
    print(f"==> Job URL: {base_url}{job_url}", file=sys.stderr)

    job = _poll_job(base_url, token, verify, job_url)
    stdout = _get_stdout(base_url, token, verify, job_url)

    output = {
        "status": job.get("status"),
        "id": job.get("id"),
        "module": MODULE,
        "module_args": args.module_args,
        "stdout": stdout,
        "failed": job.get("failed", False),
    }
    print(json.dumps(output, indent=2))
    sys.exit(1 if job.get("failed") else 0)


def cmd_launch(args: argparse.Namespace) -> None:
    """Launch a job template."""
    base_url, token, verify = _cfg()

    template_id = _resolve_id(base_url, token, verify,
                              "job_templates", args.template)

    payload: dict = {}
    if args.extra_vars:
        payload["extra_vars"] = args.extra_vars
    if args.limit:
        payload["limit"] = args.limit
    if args.inventory:
        inv_id = _resolve_id(base_url, token, verify, "inventories", args.inventory)
        payload["inventory"] = inv_id

    print(f"==> Launching job template {template_id}", file=sys.stderr)
    result = _post(
        _api(base_url, token, verify, f"/job_templates/{template_id}/launch/"),
        token, verify, payload,
    )

    job_url = result.get("url", f"{_detect_api_prefix(base_url, token, verify)}/jobs/{result['id']}/")
    print(f"==> Job URL: {base_url}{job_url}", file=sys.stderr)

    job = _poll_job(base_url, token, verify, job_url)
    stdout = _get_stdout(base_url, token, verify, job_url)

    output = {
        "status": job.get("status"),
        "id": job.get("id"),
        "template": args.template,
        "stdout": stdout,
        "failed": job.get("failed", False),
    }
    print(json.dumps(output, indent=2))
    sys.exit(1 if job.get("failed") else 0)


def cmd_status(args: argparse.Namespace) -> None:
    """Check the status of a job."""
    base_url, token, verify = _cfg()
    job_path = f"/jobs/{args.job_id}/"
    job = _get(_api(base_url, token, verify, job_path), token, verify)

    output = {
        "status": job.get("status"),
        "id": job.get("id"),
        "started": job.get("started"),
        "finished": job.get("finished"),
        "failed": job.get("failed", False),
    }
    if job.get("status") in TERMINAL_STATES:
        stdout = _get_stdout(base_url, token, verify,
                             _api(base_url, token, verify, job_path))
        output["stdout"] = stdout

    print(json.dumps(output, indent=2))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="aap_run.py",
        description=f"AAP Controller helper for {MODULE}. "
                    "Generic OS package manager",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    # -- adhoc --
    adhoc = sub.add_parser("adhoc", help=f"Run {MODULE} as an ad-hoc command via AAP")
    adhoc.add_argument("module_args", help='Module arguments (e.g. "name=nginx state=present")')
    adhoc.add_argument("--inventory", help="Inventory name or ID (or set AAP_DEFAULT_INVENTORY)")
    adhoc.add_argument("--credential", help="Credential name or ID (or set AAP_DEFAULT_CREDENTIAL)")
    adhoc.add_argument("--limit", help="Limit to specific host pattern")
    adhoc.add_argument("--no-become", action="store_true", help="Disable become/sudo")
    adhoc.add_argument("--check", action="store_true", help="Run in check/dry-run mode")
    adhoc.set_defaults(func=cmd_adhoc)

    # -- launch --
    launch = sub.add_parser("launch", help="Launch a job template via AAP")
    launch.add_argument("template", help="Job template name or ID")
    launch.add_argument("--extra-vars", help='Extra variables as JSON string')
    launch.add_argument("--limit", help="Limit to specific host pattern")
    launch.add_argument("--inventory", help="Override inventory (name or ID)")
    launch.set_defaults(func=cmd_launch)

    # -- status --
    status = sub.add_parser("status", help="Check the status of a job")
    status.add_argument("job_id", type=int, help="Job ID to check")
    status.set_defaults(func=cmd_status)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
