#!/usr/bin/env bash
# check.sh -- Prerequisite check for ansible.builtin.package
# Generated by AnsibleClaw
set -euo pipefail

MODULE="ansible.builtin.package"
COLLECTION=""
PASS=0
FAIL=0

check() {
    local label="$1"
    shift
    if "$@" > /dev/null 2>&1; then
        echo "  [PASS] $label"
        PASS=$((PASS + 1))
    else
        echo "  [FAIL] $label"
        FAIL=$((FAIL + 1))
    fi
}

echo "Checking prerequisites for $MODULE ..."
echo

check "ansible CLI is installed" command -v ansible
check "ansible-doc CLI is installed" command -v ansible-doc
check "Module $MODULE is available" ansible-doc -t module "$MODULE"

if [[ -n "$COLLECTION" ]]; then
    check "Collection $COLLECTION is installed" \
        bash -c "ansible-galaxy collection list 2>/dev/null | grep -q '$COLLECTION'"
fi

echo
echo "--- CLI Mode ---"
echo "Results: $PASS passed, $FAIL failed"

if [[ $FAIL -gt 0 ]]; then
    echo
    echo "To fix:"
    echo "  pip install ansible-core        # install Ansible"
fi

echo
echo "--- AAP Mode ---"

AAP_PASS=0
AAP_FAIL=0

aap_check() {
    local label="$1"
    shift
    if "$@" > /dev/null 2>&1; then
        echo "  [PASS] $label"
        AAP_PASS=$((AAP_PASS + 1))
    else
        echo "  [FAIL] $label"
        AAP_FAIL=$((AAP_FAIL + 1))
    fi
}

aap_check "python3 is installed" command -v python3

if [[ -n "${AAP_CONTROLLER_URL:-}" ]]; then
    echo "  [INFO] AAP_CONTROLLER_URL = ${AAP_CONTROLLER_URL}"
    aap_check "AAP_CONTROLLER_TOKEN is set" test -n "${AAP_CONTROLLER_TOKEN:-}"

    VERIFY_FLAG=""
    if [[ "${AAP_VERIFY_SSL:-true}" == "false" ]]; then
        VERIFY_FLAG="--insecure"
    fi
    aap_check "AAP Controller is reachable" \
        bash -c "curl -sf ${VERIFY_FLAG} -H 'Authorization: Bearer ${AAP_CONTROLLER_TOKEN:-}' '${AAP_CONTROLLER_URL}/api/v2/ping/' > /dev/null 2>&1 || curl -sf ${VERIFY_FLAG} -H 'Authorization: Bearer ${AAP_CONTROLLER_TOKEN:-}' '${AAP_CONTROLLER_URL}/api/controller/v2/ping/' > /dev/null 2>&1"

    aap_check "scripts/aap_run.py exists" test -f "$(dirname "$0")/aap_run.py"
else
    echo "  [SKIP] AAP_CONTROLLER_URL not set -- AAP mode not configured"
fi

echo
echo "AAP Results: $AAP_PASS passed, $AAP_FAIL failed"

if [[ $FAIL -gt 0 && $AAP_FAIL -gt 0 ]]; then
    echo
    echo "Neither CLI nor AAP mode is fully operational."
    exit 1
elif [[ $FAIL -gt 0 ]]; then
    echo
    echo "CLI mode has failures, but AAP mode is available."
elif [[ $AAP_FAIL -gt 0 && -n "${AAP_CONTROLLER_URL:-}" ]]; then
    echo
    echo "AAP mode has failures, but CLI mode is available."
fi
