#!/usr/bin/env bash
# publish_playbook.sh -- Copy skill into AAP project repo and push playbook changes
# Generated by AnsibleClaw
set -euo pipefail

SKILL_DIR_NAME="ansible_package"
DEFAULT_REPO_URL="https://github.com/micytao/AnsibleClaw-Demo.git"

USAGE="Usage: $(basename "$0") [options]

Copy this skill package into an AAP Project Git checkout at:
  skills/${SKILL_DIR_NAME}/
then commit and push the updated playbook.

Options:
  --repo-url URL      Git remote URL for the AAP Project SCM (defaults to baked hint)
  --repo-dir DIR      Local checkout directory (default: ./aap-project-repo)
  --source-dir DIR    Local skill directory to copy from (default: skill root next to scripts/)
  --commit-msg MSG    Commit message override
  --no-push           Commit but do not push
  -h, --help          Show help
"

REPO_URL="${DEFAULT_REPO_URL}"
REPO_DIR="aap-project-repo"
SOURCE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
NO_PUSH=false
COMMIT_MSG="Update ansible.builtin.package playbook and assets"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --repo-url)
            REPO_URL="${2:-}"
            shift 2
            ;;
        --repo-dir)
            REPO_DIR="${2:-}"
            shift 2
            ;;
        --source-dir)
            SOURCE_DIR="${2:-}"
            shift 2
            ;;
        --commit-msg)
            COMMIT_MSG="${2:-}"
            shift 2
            ;;
        --no-push)
            NO_PUSH=true
            shift
            ;;
        -h|--help)
            echo "$USAGE"
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            echo "$USAGE" >&2
            exit 1
            ;;
    esac
done

if ! command -v git >/dev/null 2>&1; then
    echo "Error: git is required." >&2
    exit 1
fi

if [[ ! -d "${SOURCE_DIR}" ]]; then
    echo "Error: source dir not found: ${SOURCE_DIR}" >&2
    exit 1
fi

if [[ ! -d "${REPO_DIR}/.git" ]]; then
    if [[ -z "${REPO_URL}" ]]; then
        echo "Error: repo checkout not found at ${REPO_DIR} and no --repo-url provided." >&2
        echo "Set --repo-url or configure AAP_DEFAULT_SCM_URL before generating the skill." >&2
        exit 1
    fi
    echo "==> Cloning AAP Project SCM: ${REPO_URL}"
    git clone "${REPO_URL}" "${REPO_DIR}"
fi

DEST_DIR="${REPO_DIR}/skills/${SKILL_DIR_NAME}"
mkdir -p "${DEST_DIR}"

echo "==> Syncing skill package to ${DEST_DIR}"
rm -rf "${DEST_DIR}"
mkdir -p "${DEST_DIR}"
cp -R "${SOURCE_DIR}/." "${DEST_DIR}/"

PLAYBOOK_PATH="${DEST_DIR}/assets/playbook.yml"
if [[ ! -f "${PLAYBOOK_PATH}" ]]; then
    echo "Error: playbook not found after copy: ${PLAYBOOK_PATH}" >&2
    exit 1
fi

(
    cd "${REPO_DIR}"
    git add "skills/${SKILL_DIR_NAME}/"
    if git diff --cached --quiet; then
        echo "==> No changes to commit."
        exit 0
    fi

    echo "==> Committing changes"
    git commit -m "${COMMIT_MSG}"

    if [[ "${NO_PUSH}" == "true" ]]; then
        echo "==> Commit created (push skipped due to --no-push)."
        exit 0
    fi

    echo "==> Pushing to origin"
    git push
)

echo
echo "Done. Playbook is now in repo path:"
echo "  skills/${SKILL_DIR_NAME}/assets/playbook.yml"
echo "Use this project-relative path when creating/updating the Job Template."
