#!/usr/bin/env bash
# run.sh -- Playbook runner for composite skill: web-server-setup
# Generated by AnsibleClaw (compose)
set -euo pipefail

PLAYBOOK="$(dirname "$0")/../assets/playbook.yml"
USAGE="Usage: $(basename "$0") [options]

Run the composite playbook for web-server-setup.

Modules included:
  - ansible.builtin.package
  - ansible.builtin.template
  - ansible.builtin.service
  - ansible.posix.firewalld

Options:
  --apply         Actually apply changes (default is dry-run with --check --diff)
  -i PATH         Inventory file path
  --no-become     Disable become/sudo
  -l PATTERN      Limit to specific hosts
  -e VARS         Extra variables (key=value or JSON)
  -h, --help      Show this help message

Examples:
  $(basename "$0") -i /path/to/hosts.yml
  $(basename "$0") -i /path/to/hosts.yml --apply
  $(basename "$0") -i /path/to/hosts.yml -l webservers --apply
"

APPLY=false
BECOME=true
EXTRA_FLAGS=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            echo "$USAGE"
            exit 0
            ;;
        --apply)
            APPLY=true
            shift
            ;;
        --no-become)
            BECOME=false
            shift
            ;;
        -i|-l|-e)
            EXTRA_FLAGS+=("$1" "$2")
            shift 2
            ;;
        -*)
            EXTRA_FLAGS+=("$1")
            shift
            ;;
        *)
            EXTRA_FLAGS+=("$1")
            shift
            ;;
    esac
done

CMD=(ansible-playbook "$PLAYBOOK")

if [[ "$BECOME" == false ]]; then
    CMD+=(--skip-tags become)
fi

if [[ "$APPLY" == false ]]; then
    CMD+=(--check --diff)
    echo "==> Dry-run mode (pass --apply to execute for real)"
else
    CMD+=(--diff)
    echo "==> Applying changes"
fi

CMD+=("${EXTRA_FLAGS[@]}")

echo "==> ${CMD[*]}"
exec "${CMD[@]}"
