---
# playbook.yml -- Composite playbook for web-server-setup
#
- name: "Deploy and secure an Nginx web server."
  hosts: all
  become: true
  collections:
    - ansible.posix
  tasks:
    - name: "Install Nginx"
      ansible.builtin.package:
        name: "nginx"
        state: "present"

    - name: "Ensure Nginx is started and enabled"
      ansible.builtin.service:
        name: "nginx"
        state: "started"
        enabled: true

    - name: "Permit traffic in default zone for http service"
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
